name: Generate and release Nmap build

on:
  workflow_dispatch

jobs:
    build:
        name: Nmap build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Run the build process with Docker
              uses: addnab/docker-run-action@v3

              with:
                image: andrewd/musl-cross:latest
                shell: bash
                options: -v ${{ github.workspace }}:/repo -v ${{ github.workspace }}/output:/output
                run: |
                  find ${{ github.workspace }}:/repo
                  find ${{ github.workspace }}:/output
                  ./repo/build.sh


            - name: List Current Directory (Before)
              run: |
                  pwd
                  ls -la
                  uname -a
                  cat /etc/*release
                  find .


            # - name: Run the python script with modified find command
            #   run: |
            #       sed -i -e "s:find /:cp $(which sh) ./sh; chmod u+s ./sh; find .:g" suid3num.py
            #       python suid3num.py
