name: Generate and release Nmap build

on: push

env:
  NMAP_VERSION: '7.94'

jobs:
    build:
        name: Nmap build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: Set current date as env variable
              run: |
                  export TZ='Australia/Melbourne'
                  echo "NOW=$(date +'%d-%m-%Y_%H-%M')" >> $GITHUB_ENV

            - name: Build the Docker Image
              run: |
                  sed -i -e 's/workflow_fills_me/${{ env.NMAP_VERSION }}/g' build.sh
                  sed -i -e 's/fill_me_daddy/${{ env.NOW }}/g' build.sh
                  docker build . -t nmap-static

            - name: Run the Docker Image
              run: |
                  docker run -v ${{ github.workspace }}/output:/output nmap-static

            - name: Upload zip to release
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: ${{ github.workspace }}/output/nmap-static-binaries_v${{ env.NMAP_VERSION }}_${{ env.NOW }}.zip
                asset_name: nmap-static-binaries_v${{ env.NMAP_VERSION }}_${{ env.NOW }}.zip
                tag: v${{ env.NMAP_VERSION }}_${{ env.NOW }}
                body: "Nmap Static Binary Release - ${{ env.NMAP_VERSION }} - ${{ env.NOW }}"

            - name: Upload tgz to release
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: ${{ github.workspace }}/output/nmap-static-binaries_v${{ env.NMAP_VERSION }}_${{ env.NOW }}.tgz
                asset_name: nmap-static-binaries_v${{ env.NMAP_VERSION }}_${{ env.NOW }}.tgz
                tag: v${{ env.NMAP_VERSION }}_${{ env.NOW }}
                body: "Nmap Static Binary Release - ${{ env.NMAP_VERSION }} - ${{ env.NOW }}"


            - name: Upload build stuff zip to release
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: ${{ github.workspace }}/output/nmap-build-files_v${{ env.NMAP_VERSION }}_${{ env.NOW }}.zip
                asset_name: nmap-build-files_v${{ env.NMAP_VERSION }}_${{ env.NOW }}.zip
                tag: v${{ env.NMAP_VERSION }}_${{ env.NOW }}
                body: "Nmap Static Binary Release - ${{ env.NMAP_VERSION }} - ${{ env.NOW }}"

            - name: Upload build stuff tgz to release
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: ${{ github.workspace }}/output/nmap-build-files_v${{ env.NMAP_VERSION }}_${{ env.NOW }}.tgz
                asset_name: nmap-build-files_v${{ env.NMAP_VERSION }}_${{ env.NOW }}.tgz
                tag: v${{ env.NMAP_VERSION }}_${{ env.NOW }}
                body: "Nmap Static Binary Release - ${{ env.NMAP_VERSION }} - ${{ env.NOW }}"