name: Generate and release Nmap build

on: push

env:
  NMAP_VERSION: '7.94'

jobs:
    build:
        name: Nmap build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: Check environmental variable
              run: |
                  echo ${{ env.NMAP_VERSION }}

            - name: Build the Docker Image
              run: |
                  docker build . -t nmap-static

            - name: Run the Docker Image
              run: |
                  docker run -v ${{ github.workspace }}/output:/output nmap-static

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: ${{ github.workspace }}/output/nmap-static-binaries_v${NMAP_VERSION}.zip
                asset_name: Nmap Binaries
                tag: v7.94
                body: "Nmap Static Binary Release"