name: Generate and release Nmap build

on: push

jobs:
    build:
        name: Nmap build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: Build the Docker Image
              run: |
                  docker build . -t nmap-static

            - name: Run the Docker Image
              run: |
                  docker run -v ${{ github.workspace }}/output:/output nmap-static

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: /output/nmap-build-files-7.94.zip
                asset_name: Nmap Binaries
                tag: ${{ github.ref }}
                overwrite: true
                body: "Nmap Static Binary Release"
            